config/routes.rb
FsosFe::Application.routes.draw do

  devise_for :users

  get "home/index"

  root :to => 'home#index'

  resources :charges
  resources :users  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :stripe_card_token

  def upgraded?
    return true if access_level > 0
  end

  def upgrade
    self.access_level = 1
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 900

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    current_user.upgrade
    redirect_to charges_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/charges/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $9.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="pk_test_rZf6cFxfaTVnoOWapKGsxb99"
          data-description="A month's subscription"
          data-amount="900"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FsosFe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>
<body>
  <div class="rum">
    <header>
      <h1>Sign Up Here!</h1>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
        <%= link_to "Upgrade Account", new_charge_path if not current_user.upgraded? %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </header>
    <div class="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <footer>
      <p>
        Copyright 2021
      </p>
    </footer>
  </div>

</body>
</html>